JCZL.WEBUI/JCZL.WEBUI/Models/ErrorViewModel.cs
using System;

namespace JCZL.WEBUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

JCZL.WEBUI/JCZL.WEBUI/Models/Mission.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication.Models
{
    public class Mission
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Rank { get; set; }
        public string Principal { get; set; }


    }
}

JCZL.WEBUI/JCZL.WEBUI/Models/Project.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication.Models
{
    public class Project
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Principal { get; set; }
        public string Category { get; set; }
    }
}

JCZL.WEBUI/JCZL.WEBUI/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication.Models
{
    public class User
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public int Age { get; set; }
        public string Position { get; set; }
        public string Title { get; set; }
        public string Task { get; set; }
        
    }
}

JCZL.WEBUI/JCZL.WEBUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using JCZL.WEBUI.Models;

namespace JCZL.WEBUI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

JCZL.WEBUI/JCZL.WEBUI/Controllers/MissionController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class MissionController : Controller
    {


        public IActionResult Index()
        {
            var mission = new List<Mission>() {
                new Mission(){ Id="10000",Name="设计数据库",Rank="简单",Principal="刘娜"},
                   new Mission(){ Id="10001",Name="完成用例图",Rank="中等",Principal="张建"},
                     new Mission(){ Id="10002",Name="完成ui设计",Rank="简单",Principal="小强"},
            };
            //ViewData["mission"] = mission;
            return View("Index", mission);
        }

        public IActionResult Privacy()
        {

            return View();
        }


    }
}

JCZL.WEBUI/JCZL.WEBUI/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class ProjectController : Controller
    {


        public IActionResult Index()
        {
            var project = new List<Project>() {

                new Project(){ Id=10,Name="完成用例图",Principal="刘娜",Category="开发"},
                    new Project(){ Id=1,Name="完成用例图",Principal="张建",Category="科研"},
                     new Project(){ Id=4,Name="完成用例",Principal="小明",Category="开发"},

            };
            //ViewData["project"] = project;
            return View("Index", project);
        }
        public IActionResult Privacy()
        {
            return View();
        }
    }
}

JCZL.WEBUI/JCZL.WEBUI/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            //访问数据库，获取学生列表
            var user = new List<User>() {

               new User(){ Id="10000",Name="zhangs",Sex="男",Age=28,Position="开发",Title="负责人",Task="完成用例图"},
               new User(){ Id="10001",Name="刘丹",Sex="男",Age=28,Position="开发",Title="负责人",Task="完成用例图"},
               new User(){ Id="10002",Name="赵建",Sex="男",Age=28,Position="测试",Title="员工",Task="完成数据库"},
            };
             ViewData["user"] = user;
            //return View("Index", user);
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }


    }
}

JCZL.WEBUI/JCZL.WEBUI/Views/Extra/Ssingin.cshtml
<!DOCTYPE html>
<html class="login-bg">
<head>
    <title>Detail Admin - Sign in</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- bootstrap -->
    <link href="css/bootstrap/bootstrap.css" rel="stylesheet" />
    <link href="css/bootstrap/bootstrap-responsive.css" rel="stylesheet" />
    <link href="css/bootstrap/bootstrap-overrides.css" type="text/css" rel="stylesheet" />

    <!-- global styles -->
    <link rel="stylesheet" type="text/css" href="css/layout.css" />
    <link rel="stylesheet" type="text/css" href="css/elements.css" />
    <link rel="stylesheet" type="text/css" href="css/icons.css" />

    <!-- libraries -->
    <link rel="stylesheet" type="text/css" href="css/lib/font-awesome.css" />

    <!-- this page specific styles -->
    <link rel="stylesheet" href="css/compiled/signin.css" type="text/css" media="screen" />

    <!-- open sans font -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css' />

    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>


    <!-- background switcher -->
    <div class="bg-switch visible-desktop">
        <div class="bgs">
            <a href="#" data-img="landscape.jpg" class="bg active">
                <img src="img/bgs/landscape.jpg" />
            </a>
            <a href="#" data-img="blueish.jpg" class="bg">
                <img src="img/bgs/blueish.jpg" />

        </div>
    </div>


    <div class="row-fluid login-wrapper">
        <a href="index.html">
            <img class="logo" src="img/logo-white.png" />
        </a>

        <div class="span4 box">
            <div class="content-wrap">
                <h6>Log in</h6>
                <input class="span12" type="text" placeholder="E-mail address" />
                <input class="span12" type="password" placeholder="Your password" />
                <a href="#" class="forgot">Forgot password?</a>
                <div class="remember">
                    <input id="remember-me" type="checkbox" />
                    <label for="remember-me">Remember me</label>
                </div>
                <a class="btn-glow primary login" href="index.html">Log in</a>
            </div>
        </div>

        <div class="span4 no-account">
            <p>Don't have an account?</p>
            <a href="signup.html">Sign up</a>
        </div>
    </div>

    <!-- scripts -->
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/theme.js"></script>

    <!-- pre load bg imgs -->
    <script type="text/javascript">
        $(function () {
            // bg switcher
            var $btns = $(".bg-switch .bg");
            $btns.click(function (e) {
                e.preventDefault();
                $btns.removeClass("active");
                $(this).addClass("active");
                var bg = $(this).data("img");

                $("html").css("background-image", "url('img/bgs/" + bg + "')");
            });

        });
    </script>
    <div style="display:none">
    <script src='http://v7.cnzz.com/stat.php?id=155540&web_id=155540' language='JavaScript' charset='gb2312'></script></div>
</body>
</html>

JCZL.WEBUI/JCZL.WEBUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

JCZL.WEBUI/JCZL.WEBUI/Views/Mission/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    //var mission = ViewData["Mission"] as List<Mission>;
    var mission = Model;
}

<!DOCTYPE html>
<html>
<head>
    <title>Detail Admin - User list</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- bootstrap -->
    <link href="css/bootstrap/bootstrap.css" rel="stylesheet" />
    <link href="css/bootstrap/bootstrap-responsive.css" rel="stylesheet" />
    <link href="css/bootstrap/bootstrap-overrides.css" type="text/css" rel="stylesheet" />

    <!-- global styles -->
    <link rel="stylesheet" type="text/css" href="css/layout.css" />
    <link rel="stylesheet" type="text/css" href="css/elements.css" />
    <link rel="stylesheet" type="text/css" href="css/icons.css" />

    <!-- libraries -->
    <link href="css/lib/font-awesome.css" type="text/css" rel="stylesheet" />

    <!-- this page specific styles -->
    <link rel="stylesheet" href="css/compiled/user-list.css" type="text/css" media="screen" />

    <!-- open sans font -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css' />

    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>
    <div class="container-fluid">
        <div id="pad-wrapper" class="users-list">
            <div class="row-fluid header">
                <h3>任务列表</h3>
                <div class="span10 pull-right">
                    <input type="text" class="span5 search" placeholder="Type a user's name..." />

                    <!-- custom popup filter -->
                    <!-- styles are located in css/elements.css -->
                    <!-- script that enables this dropdown is located in js/theme.js -->
                    <div class="ui-dropdown">
                        <div class="head" data-toggle="tooltip" title="Click me!">
                            Filter users
                            <i class="arrow-down"></i>
                        </div>
                        <div class="dialog">
                            <div class="pointer">
                                <div class="arrow"></div>
                                <div class="arrow_border"></div>
                            </div>
                            <div class="body">
                                <p class="title">
                                    Show users where:
                                </p>
                                <div class="form">
                                    <select>
                                        <option />Name
                                        <option />Email
                                        <option />Number of orders
                                        <option />Signed up
                                        <option />Last seen
                                    </select>
                                    <select>
                                        <option />is equal to
                                        <option />is not equal to
                                        <option />is greater than
                                        <option />starts with
                                        <option />contains
                                    </select>
                                    <input type="text" />
                                    <a class="btn-flat small">Add filter</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <a href="new-user.html" class="btn-flat success pull-right">
                        <span>&#43;</span>
                        new
                    </a>
                </div>
            </div>

            <!-- Users table -->
            <div class="row-fluid table">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th class="span2 sortable">
                                编号
                            </th>
                            <th class="span2 sortable">
                                <span class="line"></span> 名称
                            </th>
                            <th class="span1 sortable">
                                <span class="line"></span>等级
                            </th>
                            <th class="span2 sortable">
                                <span class="line"></span>负责人
                            </th>
                            <th class="span2 sortable">
                                <span class="line"></span>操作
                            </th>



                        </tr>
                    </thead>
                    <tbody>
                        <!-- row -->
                        @for (int i = 0; i < mission.Count; i++)
                        {

                            <tr>
                                <td>@mission[i].Id</td>
                                <td>@mission[i].Name</td>
                                <td>@mission[i].Rank</td>
                                <td>@mission[i].Principal</td>

                                <td>
                                    <button type="button" class="btn btn-primary" onclick="showItem(@mission[i].Id)">查看</button>
                                    <button type="button" class="btn btn-primary" onclick="showItem(@mission[i].Id)">删除</button>
                                    <button type="button" class="btn btn-primary" onclick="showItem(@mission[i].Id)">编辑</button>

                                    <button type="button" class="btn btn-primary" onclick="showItem(@mission[i].Id)">分配任务</button>
                                </td>
                            </tr>

                        }

                    </tbody>
                </table>
            </div>
            <div class="pagination pull-right">
                <ul>
                    <li><a href="#">&#8249;</a></li>
                    <li><a class="active" href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">5</a></li>
                    <li><a href="#">&#8250;</a></li>
                </ul>
            </div>
            <!-- end users table -->
        </div>
    </div>
    <!-- end main container -->
    <!-- scripts -->
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/theme.js"></script>
    <div style="display:none">
        <script src='http://v7.cnzz.com/stat.php?id=155540&web_id=155540' language='JavaScript' charset='gb2312'></script>
    </div>
</body>
</html>















s

JCZL.WEBUI/JCZL.WEBUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Detail Admin - Home</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- bootstrap -->
    <link href="~/css/bootstrap/bootstrap.css" rel="stylesheet" />
    <link href="~/css/bootstrap/bootstrap-responsive.css" rel="stylesheet" />
    <link href="~/css/bootstrap/bootstrap-overrides.css" type="text/css" rel="stylesheet" />

    <!-- libraries -->
    <link href="~/css/lib/jquery-ui-1.10.2.custom.css" rel="stylesheet" type="text/css" />
    <link href="~/css/lib/font-awesome.css" type="text/css" rel="stylesheet" />

    <!-- global styles -->
    <link rel="stylesheet" type="text/css" href="~/css/layout.css" />
    <link rel="stylesheet" type="text/css" href="~/css/elements.css" />
    <link rel="stylesheet" type="text/css" href="~/css/icons.css" />


    <!-- this page specific styles -->
    <link rel="stylesheet" href="css/compiled/index.css" type="text/css" media="screen" />


    <!-- open sans font -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css' />

    <!-- lato font -->
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css' />

    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>

    <!-- navbar -->
    <div class="navbar navbar-inverse">
        <div class="navbar-inner">
            <button type="button" class="btn btn-navbar visible-phone" id="menu-toggler">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="brand" href="index.html">
                <img src="img/craftsman-logo.png" style="width:30px;height:30px;" />
                <span style="text-transform:capitalize">基础资料管理系统 </span>
            </a>
            <ul class="nav pull-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle hidden-phone" data-toggle="dropdown">
                        Your account
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="personal-info.html">Personal info</a></li>
                        <li><a href="#">Account settings</a></li>
                        <li><a href="#">Billing</a></li>
                        <li><a href="#">Export your data</a></li>
                        <li><a href="#">Send feedback</a></li>
                    </ul>
                </li>
                <li class="settings hidden-phone">
                    <a href="personal-info.html" role="button">
                        <i class="icon-cog"></i>
                    </a>
                </li>
                <li class="settings hidden-phone">
                    <a href="signin.html" role="button">
                        <i class="icon-share-alt"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <!-- end navbar -->
    <!-- sidebar -->
    <div id="sidebar-nav">
        <ul id="dashboard-menu">
            <li class="active">
                <div class="pointer">
                    <div class="arrow"></div>
                    <div class="arrow_border"></div>
                </div>
                <a href='@Url.Action("Index","Home")'>
                    <i class="icon-home"></i>
                    <span>主页</span>
                </a>
            </li>

            <li>
                <a class="dropdown-toggle" href="#">
                    <i class="icon-group"></i>
                    <span>用户管理</span>
                    <i class="icon-chevron-down"></i>
                </a>
                <ul class="submenu">
                    <li><a href='@Url.Action("Index","User")'>用户列表</a></li>
                    <li><a href='@Url.Action("Privacy","User")'>用户状态</a></li>
                </ul>
            </li>
            <li>
                <a class="dropdown-toggle" href="#">
                    <i class="icon-code-fork"></i>
                    <span>项目管理</span>
                    <i class="icon-chevron-down"></i>
                </a>
                <ul class="submenu">
                    <li><a href='@Url.Action("Index","Project")'>项目列表</a></li>
                    <li><a href='@Url.Action("Privacy","Project")'>项目状态</a></li>
                </ul>
            </li>

            <li>
                <a class="dropdown-toggle" href="#">
                    <i class="icon-tasks"></i>
                    <span>任务管理</span>
                    <i class="icon-chevron-down"></i>
                </a>
                <ul class="submenu">
                    <li><a href='@Url.Action("Index","Mission")'>任务列表</a></li>
                    <li><a href='@Url.Action("Privacy","Mission")'>任务状态</a></li>
                </ul>
            </li>

            <li>
                <a class="dropdown-toggle" href="#">
                    <i class="icon-share-alt"></i>
                    <span>其他</span>
                    <i class="icon-chevron-down"></i>
                </a>
                <ul class="submenu">
                    <li><a href="~/signin.html">登录</a></li>
                    <li><a href="new-user.html">退出</a></li>

                </ul>
            </li>
        </ul>
    </div>
    <!-- end sidebar -->
    <!-- main container -->
    <div class="content">
        <div id="ajax-content">
            @RenderBody()
        </div>



        <!-- scripts -->
        <script src="http://code.jquery.com/jquery-latest.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/jquery-ui-1.10.2.custom.min.js"></script>
        <!-- knob -->
        <script src="js/jquery.knob.js"></script>
        <!-- flot charts -->
        <script src="js/jquery.flot.js"></script>
        <script src="js/jquery.flot.stack.js"></script>
        <script src="js/jquery.flot.resize.js"></script>
        <script src="js/theme.js"></script>

        <script type="text/javascript">
            $(function () {

                // jQuery Knobs
                $(".knob").knob();



                // jQuery UI Sliders
                $(".slider-sample1").slider({
                    value: 100,
                    min: 1,
                    max: 500
                });
                $(".slider-sample2").slider({
                    range: "min",
                    value: 130,
                    min: 1,
                    max: 500
                });
                $(".slider-sample3").slider({
                    range: true,
                    min: 0,
                    max: 500,
                    values: [40, 170],
                });



                // jQuery Flot Chart
                var failedCase = [[1, 50], [2, 40], [3, 45], [4, 23], [5, 55], [6, 65], [7, 61], [8, 70], [9, 65], [10, 75], [11, 57], [12, 59]];
                var successCase = [[1, 25], [2, 50], [3, 23], [4, 48], [5, 38], [6, 40], [7, 47], [8, 55], [9, 43], [10, 50], [11, 47], [12, 39]];

                var plot = $.plot($("#statsChart"),
                    [{ data: failedCase, label: "Failed" },
                    { data: successCase, label: "Success" }], {
                        series: {
                            lines: {
                                show: true,
                                lineWidth: 1,
                                fill: true,
                                fillColor: { colors: [{ opacity: 0.1 }, { opacity: 0.13 }] }
                            },
                            points: {
                                show: true,
                                lineWidth: 2,
                                radius: 3
                            },
                            shadowSize: 0,
                            stack: true
                        },
                        grid: {
                            hoverable: true,
                            clickable: true,
                            tickColor: "#f9f9f9",
                            borderWidth: 0
                        },
                        legend: {
                            // show: false
                            labelBoxBorderColor: "#fff"
                        },
                        colors: ["#a7b5c5", "#30a0eb"],
                        xaxis: {
                            ticks: [[1, "Round 01"], [2, "Round 02"], [3, "Round 03"], [4, "Round 04"], [5, "Round 05"], [6, "Round 06"],
                            [7, "Round 07"], [8, "Round 08"], [9, "Round 09"], [10, "Round 10"], [11, "Round 11"], [12, "Round 12"]],
                            font: {
                                size: 12,
                                family: "Open Sans, Arial",
                                variant: "small-caps",
                                color: "#697695"
                            }
                        },
                        yaxis: {
                            ticks: 3,
                            tickDecimals: 0,
                            font: { size: 12, color: "#9da3a9" }
                        }
                    });

                function showTooltip(x, y, contents) {
                    $('<div id="tooltip">' + contents + '</div>').css({
                        position: 'absolute',
                        display: 'none',
                        top: y - 30,
                        left: x - 50,
                        color: "#fff",
                        padding: '2px 5px',
                        'border-radius': '6px',
                        'background-color': '#000',
                        opacity: 0.80
                    }).appendTo("body").fadeIn(200);
                }

                var previousPoint = null;
                $("#statsChart").bind("plothover", function (event, pos, item) {
                    if (item) {
                        if (previousPoint != item.dataIndex) {
                            previousPoint = item.dataIndex;

                            $("#tooltip").remove();
                            var x = item.datapoint[0].toFixed(0),
                                y = item.datapoint[1].toFixed(0);

                            var month = item.series.xaxis.ticks[item.dataIndex].label;

                            showTooltip(item.pageX, item.pageY,
                                item.series.label + " of " + month + ": " + y);
                        }
                    }
                    else {
                        $("#tooltip").remove();
                        previousPoint = null;
                    }
                });
            });
        </script>
        @RenderSection("Myscripts", required: false)
</body>
</html>